-- this file is generated by program!
-- don't change it manaully.
-- source file: common_skill
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end




return class_data
