-- this file is generated by program!
-- don't change it manaully.
-- source file: copy
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[90000] = { copyid = 90000,  born_condition_id = {},  copy_sence_id = 2,  order = 1}
data[90001] = { copyid = 90001,  born_condition_id = {21,22,23,24,25},  copy_sence_id = 2,  order = 1}
data[90002] = { copyid = 90002,  born_condition_id = {},  copy_sence_id = 2,  order = 1}
data[90003] = { copyid = 90003,  born_condition_id = {21,29,30,31,32,33},  copy_sence_id = 2,  order = 1}

return class_data
