-- this file is generated by program!
-- don't change it manaully.
-- source file: copy_enemy
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end




function class_data.getDataByIndexOne(copy_id)

    if index_one_data == nil then
      class_data.initIndexOneData()
    end

    return index_one_data[copy_id]
end

function class_data.initIndexOneData()
    index_one_data = {}
    for k,v in pairs(data) do
        if index_one_data[v.copy_id] == nil then
          index_one_data[v.copy_id] = {}
        end

        index_one_data[v.copy_id][v.id] = v

    end
end
		
data[1] = { id = 1,  copy_id = 90000,  order = 1,  hero_id = 112,  pos_id = 1,  common_attribute_id = 0}
data[2] = { id = 2,  copy_id = 90000,  order = 1,  hero_id = 113,  pos_id = 2,  common_attribute_id = 0}
data[3] = { id = 3,  copy_id = 90000,  order = 1,  hero_id = 114,  pos_id = 3,  common_attribute_id = 0}
data[4] = { id = 4,  copy_id = 90000,  order = 1,  hero_id = 115,  pos_id = 4,  common_attribute_id = 0}
data[5] = { id = 5,  copy_id = 90001,  order = 1,  hero_id = 116,  pos_id = 1,  common_attribute_id = 0}
data[6] = { id = 6,  copy_id = 90001,  order = 1,  hero_id = 117,  pos_id = 2,  common_attribute_id = 0}
data[7] = { id = 7,  copy_id = 90001,  order = 1,  hero_id = 118,  pos_id = 3,  common_attribute_id = 0}
data[8] = { id = 8,  copy_id = 90001,  order = 1,  hero_id = 119,  pos_id = 4,  common_attribute_id = 0}
data[9] = { id = 9,  copy_id = 90001,  order = 2,  hero_id = 116,  pos_id = 1,  common_attribute_id = 0}
data[10] = { id = 10,  copy_id = 90001,  order = 2,  hero_id = 117,  pos_id = 2,  common_attribute_id = 0}
data[11] = { id = 11,  copy_id = 90001,  order = 2,  hero_id = 118,  pos_id = 3,  common_attribute_id = 0}
data[12] = { id = 12,  copy_id = 90001,  order = 2,  hero_id = 119,  pos_id = 4,  common_attribute_id = 0}
data[13] = { id = 13,  copy_id = 90001,  order = 3,  hero_id = 116,  pos_id = 1,  common_attribute_id = 0}
data[14] = { id = 14,  copy_id = 90001,  order = 3,  hero_id = 117,  pos_id = 2,  common_attribute_id = 0}
data[15] = { id = 15,  copy_id = 90001,  order = 3,  hero_id = 118,  pos_id = 3,  common_attribute_id = 0}
data[16] = { id = 16,  copy_id = 90001,  order = 3,  hero_id = 119,  pos_id = 4,  common_attribute_id = 0}
data[17] = { id = 17,  copy_id = 90001,  order = 3,  hero_id = 112,  pos_id = 5,  common_attribute_id = 0}
data[18] = { id = 18,  copy_id = 90001,  order = 3,  hero_id = 117,  pos_id = 6,  common_attribute_id = 0}
data[19] = { id = 19,  copy_id = 90001,  order = 4,  hero_id = 112,  pos_id = 1,  common_attribute_id = 0}
data[20] = { id = 20,  copy_id = 90002,  order = 1,  hero_id = 112,  pos_id = 1,  common_attribute_id = 0}
data[21] = { id = 21,  copy_id = 90002,  order = 1,  hero_id = 113,  pos_id = 2,  common_attribute_id = 0}
data[22] = { id = 22,  copy_id = 90002,  order = 1,  hero_id = 114,  pos_id = 3,  common_attribute_id = 0}
data[23] = { id = 23,  copy_id = 90002,  order = 1,  hero_id = 115,  pos_id = 4,  common_attribute_id = 0}
data[24] = { id = 24,  copy_id = 90002,  order = 1,  hero_id = 116,  pos_id = 5,  common_attribute_id = 0}
data[25] = { id = 25,  copy_id = 90002,  order = 1,  hero_id = 117,  pos_id = 6,  common_attribute_id = 0}
data[26] = { id = 26,  copy_id = 90003,  order = 1,  hero_id = 116,  pos_id = 1,  common_attribute_id = 0}
data[27] = { id = 27,  copy_id = 90003,  order = 1,  hero_id = 117,  pos_id = 2,  common_attribute_id = 0}
data[28] = { id = 28,  copy_id = 90003,  order = 1,  hero_id = 118,  pos_id = 3,  common_attribute_id = 0}
data[29] = { id = 29,  copy_id = 90003,  order = 1,  hero_id = 119,  pos_id = 4,  common_attribute_id = 0}
data[30] = { id = 30,  copy_id = 90003,  order = 1,  hero_id = 112,  pos_id = 5,  common_attribute_id = 0}
data[31] = { id = 31,  copy_id = 90003,  order = 1,  hero_id = 117,  pos_id = 6,  common_attribute_id = 0}
data[32] = { id = 32,  copy_id = 90003,  order = 2,  hero_id = 116,  pos_id = 1,  common_attribute_id = 0}
data[33] = { id = 33,  copy_id = 90003,  order = 2,  hero_id = 117,  pos_id = 2,  common_attribute_id = 0}
data[34] = { id = 34,  copy_id = 90003,  order = 2,  hero_id = 118,  pos_id = 3,  common_attribute_id = 0}
data[35] = { id = 35,  copy_id = 90003,  order = 2,  hero_id = 119,  pos_id = 4,  common_attribute_id = 0}
data[36] = { id = 36,  copy_id = 90003,  order = 2,  hero_id = 112,  pos_id = 5,  common_attribute_id = 0}
data[37] = { id = 37,  copy_id = 90003,  order = 2,  hero_id = 117,  pos_id = 6,  common_attribute_id = 0}

return class_data
