-- this file is generated by program!
-- don't change it manaully.
-- source file: effect_bone_type
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["body"] = { id = "body",  desc = "身体",  todo = ""}
data["feet"] = { id = "feet",  desc = "脚",  todo = ""}

return class_data
