-- this file is generated by program!
-- don't change it manaully.
-- source file: effect_resource
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[2000001] = { id = 2000001,  url = "effects/pokemon/0002_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[2000002] = { id = 2000002,  url = "effects/pokemon/0002_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[2000003] = { id = 2000003,  url = "effects/pokemon/0002_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[25000002] = { id = 25000002,  url = "effects/pokemon/0025_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[82000001] = { id = 82000001,  url = "effects/pokemon/0082_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[445000002] = { id = 445000002,  url = "effects/pokemon/0445_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[82000002] = { id = 82000002,  url = "effects/pokemon/0082_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[717000001] = { id = 717000001,  url = "effects/pokemon/0717_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[25000003] = { id = 25000003,  url = "effects/pokemon/0025_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[716000004] = { id = 716000004,  url = "effects/pokemon/0716_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[716000002] = { id = 716000002,  url = "effects/pokemon/0716_00_00_attack_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[6020001] = { id = 6020001,  url = "effects/pokemon/0006_02_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[6020002] = { id = 6020002,  url = "effects/pokemon/0006_02_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[6020003] = { id = 6020003,  url = "effects/pokemon/0006_02_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[82000003] = { id = 82000003,  url = "effects/pokemon/0082_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[445000003] = { id = 445000003,  url = "effects/pokemon/0445_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[717000002] = { id = 717000002,  url = "effects/pokemon/0717_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[11190] = { id = 11190,  url = "effects/huoqiushu_qiu",  duration = 1.06,  is_loop = 0,  bone_type = ""}
data[716000003] = { id = 716000003,  url = "effects/pokemon/0716_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[9000001] = { id = 9000001,  url = "effects/pokemon/0009_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[9000002] = { id = 9000002,  url = "effects/pokemon/0009_00_00_skill_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[9000003] = { id = 9000003,  url = "effects/pokemon/0009_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[717000003] = { id = 717000003,  url = "effects/pokemon/0717_00_00_skill_hit",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[25000001] = { id = 25000001,  url = "effects/pokemon/0025_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[100] = { id = 100,  url = "effects/weather/01sunny",  duration = 0.0,  is_loop = 0,  bone_type = ""}
data[101] = { id = 101,  url = "effects/weather/01verysunny",  duration = 0.0,  is_loop = 0,  bone_type = ""}
data[102] = { id = 102,  url = "effects/weather/02dark",  duration = 0.0,  is_loop = 0,  bone_type = ""}
data[103] = { id = 103,  url = "effects/weather/01rain",  duration = 0.0,  is_loop = 0,  bone_type = ""}
data[445000001] = { id = 445000001,  url = "effects/pokemon/0445_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}
data[11119] = { id = 11119,  url = "effects/huoqiushu_qiu",  duration = 1.06,  is_loop = 0,  bone_type = "body"}
data[11120] = { id = 11120,  url = "effects/huoqiushu_daji",  duration = 0.6,  is_loop = 0,  bone_type = "body"}
data[716000001] = { id = 716000001,  url = "effects/pokemon/0716_00_00_attack_cast",  duration = 2.0,  is_loop = 0,  bone_type = ""}

return class_data
