-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_skill_release
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end




function class_data.getDataByIndexOne(skill_id)

    if index_one_data == nil then
      class_data.initIndexOneData()
    end

    return index_one_data[skill_id]
end

function class_data.initIndexOneData()
    index_one_data = {}
    for k,v in pairs(data) do
        if index_one_data[v.skill_id] == nil then
          index_one_data[v.skill_id] = {}
        end

        index_one_data[v.skill_id][v.id] = v

    end
end
		
data["116_normal_1_release_1"] = { id = "116_normal_1_release_1",  skill_id = "116_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["117_utl_1_release_1"] = { id = "117_utl_1_release_1",  skill_id = "117_utl_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {445000003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["113_utl_1_release_1"] = { id = "113_utl_1_release_1",  skill_id = "113_utl_1",  project_id = "",  project_release_time = 0,  release_time = 1.3,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {6020003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["112_utl_1_release_1"] = { id = "112_utl_1_release_1",  skill_id = "112_utl_1",  project_id = "",  project_release_time = 0,  release_time = 0.9,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {2000003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["115_utl_1_release_1"] = { id = "115_utl_1_release_1",  skill_id = "115_utl_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {25000003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["115_normal_1_release_1"] = { id = "115_normal_1_release_1",  skill_id = "115_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["114_normal_1_release_1"] = { id = "114_normal_1_release_1",  skill_id = "114_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["116_utl_1_release_1"] = { id = "116_utl_1_release_1",  skill_id = "116_utl_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {82000003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["118_utl_1_release_1"] = { id = "118_utl_1_release_1",  skill_id = "118_utl_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {716000004},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["117_normal_1_release_1"] = { id = "117_normal_1_release_1",  skill_id = "117_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["113_normal_1_release_1"] = { id = "113_normal_1_release_1",  skill_id = "113_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["119_utl_1_release_1"] = { id = "119_utl_1_release_1",  skill_id = "119_utl_1",  project_id = "",  project_release_time = 0,  release_time = 1.0,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {717000003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["118_normal_1_release_1"] = { id = "118_normal_1_release_1",  skill_id = "118_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {716000002},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["112_normal_1_release_1"] = { id = "112_normal_1_release_1",  skill_id = "112_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["114_utl_1_release_1"] = { id = "114_utl_1_release_1",  skill_id = "114_utl_1",  project_id = "",  project_release_time = 0,  release_time = 1.1,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {9000003},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 30.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}
data["119_normal_1_release_1"] = { id = "119_normal_1_release_1",  skill_id = "119_normal_1",  project_id = "",  project_release_time = 0,  release_time = 0.5,  buff_id_s = {},  ignore_buff_factor_s = {},  summon_id_s = {},  release_effect_id_s = {},  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  export_dmg_type = "fei",  default_dmg_num = 10.0,  growup_dmg_num = 1.0,  default_dmg_factor_num = 0,  growup_dmg_factor_num = 0,  be_hit_audio = "",  behit_animation_name = {},  attack_audio = ""}

return class_data
