-- this file is generated by program!
-- don't change it manaully.
-- source file: hero
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[112] = { id = 112,  name = "妙蛙种子",  resoure_name = "0002_00_00",  default_hp = 15000.0,  default_attack = 300.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 90.0,  radius = 1.4,  height = 1.8}
data[113] = { id = 113,  name = "小火龙",  resoure_name = "0006_02_00",  default_hp = 100000.0,  default_attack = 400.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 99.0,  radius = 1.4,  height = 1.8}
data[114] = { id = 114,  name = "杰尼龟",  resoure_name = "0009_00_00",  default_hp = 120000.0,  default_attack = 500.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 108.0,  radius = 1.4,  height = 1.8}
data[115] = { id = 115,  name = "皮卡丘",  resoure_name = "0025_00_00",  default_hp = 130000.0,  default_attack = 600.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 117.0,  radius = 1.4,  height = 1.8}
data[116] = { id = 116,  name = "电池",  resoure_name = "0082_00_00",  default_hp = 14000.0,  default_attack = 700.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 126.0,  radius = 1.4,  height = 1.8}
data[117] = { id = 117,  name = "烈陆咬鲨",  resoure_name = "0445_00_00",  default_hp = 15000.0,  default_attack = 800.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 135.0,  radius = 1.4,  height = 1.8}
data[118] = { id = 118,  name = "哲尔尼亚斯",  resoure_name = "0716_00_00",  default_hp = 16000.0,  default_attack = 900.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 144.0,  radius = 1.4,  height = 1.8}
data[119] = { id = 119,  name = "伊裴尔塔尔",  resoure_name = "0717_00_00",  default_hp = 17000.0,  default_attack = 1000.0,  default_mag_defence = 200.0,  default_phy_defence = 200.0,  attack_speed = 153.0,  radius = 1.4,  height = 1.8}

return class_data
