-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_res
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["0006_02_00"] = { prefab_name = "0006_02_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0006_02_00/0006_02_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0006_02_00",  path_anim = "Models/hero/0006_02_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0009_00_00"] = { prefab_name = "0009_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0009_00_00/0009_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0009_00_00",  path_anim = "Models/hero/0009_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0717_00_00"] = { prefab_name = "0717_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0717_00_00/0717_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0717_00_00",  path_anim = "Models/hero/0717_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["dunzhan_1"] = { prefab_name = "dunzhan_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/dunzhan_1/dunzhan_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/dunzhan_1/ani",  path_anim = "Models/hero/dunzhan_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["gongzhu_summon_1"] = { prefab_name = "gongzhu_summon_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/gongzhu_summon_1/gongzhu_summon_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/gongzhu_summon_1/ani",  path_anim = "Models/hero/gongzhu_summon_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0716_00_00"] = { prefab_name = "0716_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0716_00_00/0716_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0716_00_00",  path_anim = "Models/hero/0716_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["gongzhu_1"] = { prefab_name = "gongzhu_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/gongzhu_1/gongzhu_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/gongzhu_1/ani",  path_anim = "Models/hero/gongzhu_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["fashi_1"] = { prefab_name = "fashi_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/fashi_1/fashi_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/fashi_1/ani",  path_anim = "Models/hero/fashi_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["monster_2"] = { prefab_name = "monster_2",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/monster_2/monster_2.FBX",  source_path_anim = "Clilent/Res/Models/hero/monster_2/ani",  path_anim = "Models/hero/monster_2/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["monster_1"] = { prefab_name = "monster_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/monster_1/monster_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/monster_1/ani",  path_anim = "Models/hero/monster_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0445_00_00"] = { prefab_name = "0445_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0445_00_00/0445_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0445_00_00",  path_anim = "Models/hero/0445_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0002_00_00"] = { prefab_name = "0002_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0002_00_00/0002_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0002_00_00",  path_anim = "Models/hero/0002_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["mushi_1"] = { prefab_name = "mushi_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/mushi_1/mushi_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/mushi_1/ani",  path_anim = "Models/hero/mushi_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["zhujiao_1"] = { prefab_name = "zhujiao_1",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/zhujiao_1/zhujiao_1.FBX",  source_path_anim = "Clilent/Res/Models/hero/zhujiao_1/ani",  path_anim = "Models/hero/zhujiao_1/ani",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0082_00_00"] = { prefab_name = "0082_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0082_00_00/0082_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0082_00_00",  path_anim = "Models/hero/0082_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}
data["0025_00_00"] = { prefab_name = "0025_00_00",  grp_type = 1,  layer = "Battle",  path_model = "Clilent/Res/Models/hero/0025_00_00/0025_00_00.FBX",  source_path_anim = "Clilent/Res/Models/hero/0025_00_00",  path_anim = "Models/hero/0025_00_00",  path_main_tex = "",  path_mask_tex = "",  path_mat_template = ""}

return class_data
