-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_summon
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["summon_1"] = { id = "summon_1",  hero_id = 0,  common_attribute_id = 0,  common_monster_skill_id = 0,  lift_time = 0}

return class_data
