-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_skill_release_project
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["project_001"] = { id = "project_001",  init_center = 0,  projectile_default_x = 0.0,  projectile_default_y = 1.0,  projectile_default_z = -1.0,  target_center = 1,  target_x = 0.0,  target_y = 1.0,  target_z = 1.0,  project_curve_type = "line",  effect_res_id = 11119}
data["project_002"] = { id = "project_002",  init_center = 0,  projectile_default_x = 0.0,  projectile_default_y = 1.0,  projectile_default_z = -1.0,  target_center = 0,  target_x = 0.0,  target_y = 1.0,  target_z = 1.0,  project_curve_type = "curve",  effect_res_id = 11119}

return class_data
