-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_skill_release_buff
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["buff_chengmo"] = { id = "buff_chengmo",  buff_name = "沉默",  hero_class = "",  buff_class = "0.0",  replace_type = "0.0",  benefit_type = "2.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "iinflunce_chngmo",  default_factor = 0.0,  growup_factor = 0.0,  val_type = "a",  target_type = "friend",  buffer_position_type = "",  display_effect_url = ""}
data["buff_chaofeng"] = { id = "buff_chaofeng",  buff_name = "嘲讽",  hero_class = "",  buff_class = "0.0",  replace_type = "0.0",  benefit_type = "2.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "influnce_chaofeng",  default_factor = 0,  growup_factor = 0,  val_type = "",  target_type = "",  buffer_position_type = "",  display_effect_url = "buff/buff_chaofeng"}
data["buff_mianyikongzhi"] = { id = "buff_mianyikongzhi",  buff_name = "免疫控制",  hero_class = "",  buff_class = "0.0",  replace_type = "0.0",  benefit_type = "1.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "influnce_mianyikongzhi",  default_factor = 0,  growup_factor = 0,  val_type = "",  target_type = "friend",  buffer_position_type = "",  display_effect_url = "buff/buff_miankong"}
data["buff_wudi"] = { id = "buff_wudi",  buff_name = "自身无敌",  hero_class = "",  buff_class = "0.0",  replace_type = "1.0",  benefit_type = "1.0",  clear_types = {},  default_time = 4.0,  count = 0,  factor_type = "influnce_wudi",  default_factor = 0.0,  growup_factor = 0.0,  val_type = "a",  target_type = "enemy",  buffer_position_type = "",  display_effect_url = ""}
data["buff_jiaoxie"] = { id = "buff_jiaoxie",  buff_name = "缴械",  hero_class = "",  buff_class = "0.0",  replace_type = "0.0",  benefit_type = "2.0",  clear_types = {},  default_time = 4.0,  count = 0,  factor_type = "influnce_jiaoxie",  default_factor = 0.0,  growup_factor = 0.0,  val_type = "a",  target_type = "friend",  buffer_position_type = "arm",  display_effect_url = "buff/buff_jiaoxie"}
data["buff_xuanyun"] = { id = "buff_xuanyun",  buff_name = "眩晕",  hero_class = "",  buff_class = "0.0",  replace_type = "2.0",  benefit_type = "2.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "influnce_xuanyun",  default_factor = 0.0,  growup_factor = 0.0,  val_type = "a",  target_type = "friend",  buffer_position_type = "feet",  display_effect_url = "buff/buff_xuanyun"}
data["buff_meihuo"] = { id = "buff_meihuo",  buff_name = "魅惑",  hero_class = "",  buff_class = "0.0",  replace_type = "0.0",  benefit_type = "2.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "influnce_meihuo",  default_factor = 0.0,  growup_factor = 0.0,  val_type = "a",  target_type = "friend",  buffer_position_type = "body",  display_effect_url = "buff/buff_meihuo"}
data["buff_dingshen"] = { id = "buff_dingshen",  buff_name = "定身",  hero_class = "",  buff_class = "",  replace_type = "",  benefit_type = "2.0",  clear_types = {},  default_time = 0,  count = 0,  factor_type = "influnce_dingshen",  default_factor = 0,  growup_factor = 0,  val_type = "",  target_type = "friend",  buffer_position_type = "",  display_effect_url = ""}
data["buff_max_hp_sp1"] = { id = "buff_max_hp_sp1",  buff_name = "特性系最大血量百分比掉血",  hero_class = "huo&&gang",  buff_class = "",  replace_type = "",  benefit_type = "",  clear_types = {},  default_time = 0,  count = 0,  factor_type = "",  default_factor = 0,  growup_factor = 0,  val_type = "",  target_type = "",  buffer_position_type = "",  display_effect_url = ""}
data["bufff_jinggu"] = { id = "bufff_jinggu",  buff_name = "禁锢",  hero_class = "",  buff_class = "0.0",  replace_type = "0.0",  benefit_type = "3.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "influnce_jinggu",  default_factor = 0,  growup_factor = 0,  val_type = "",  target_type = "",  buffer_position_type = "",  display_effect_url = ""}
data["buff_kongju"] = { id = "buff_kongju",  buff_name = "恐惧",  hero_class = "",  buff_class = "0.0",  replace_type = "2.0",  benefit_type = "1.0",  clear_types = {},  default_time = 5.0,  count = 0,  factor_type = "influnce_kongju",  default_factor = 0,  growup_factor = 0,  val_type = "",  target_type = "",  buffer_position_type = "",  display_effect_url = "buff/buff_kongju"}

return class_data
