-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_skill
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end




function class_data.getDataByIndexOne(heroId)

    if index_one_data == nil then
      class_data.initIndexOneData()
    end

    return index_one_data[heroId]
end

function class_data.initIndexOneData()
    index_one_data = {}
    for k,v in pairs(data) do
        if index_one_data[v.heroId] == nil then
          index_one_data[v.heroId] = {}
        end

        index_one_data[v.heroId][v.id] = v

    end
end
		
data["119_utl_1"] = { id = "119_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 119,  resoure_name = "0717_00_00",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.6,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {717000002}}
data["119_normal_1"] = { id = "119_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 119,  resoure_name = "0717_00_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.3,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {717000001}}
data["117_utl_1"] = { id = "117_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 117,  resoure_name = "0445_00_01",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.3,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {445000002}}
data["112_normal_1"] = { id = "112_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 112,  resoure_name = "0002_00_00",  skill_name = "普攻",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.3,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {2000001}}
data["115_normal_1"] = { id = "115_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 115,  resoure_name = "0025_00_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.0,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {25000001}}
data["118_normal_1"] = { id = "118_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 118,  resoure_name = "0716_00_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.1,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {716000001}}
data["112_utl_1"] = { id = "112_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 112,  resoure_name = "0002_00_00",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.6,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {2000002}}
data["114_normal_1"] = { id = "114_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 114,  resoure_name = "0009_00_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.3,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {9000001}}
data["115_utl_1"] = { id = "115_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 115,  resoure_name = "0025_00_00",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.3,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {25000002}}
data["114_utl_1"] = { id = "114_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 114,  resoure_name = "0009_00_00",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.6,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {9000002}}
data["113_utl_1"] = { id = "113_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 113,  resoure_name = "0006_02_00",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 2.15,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {6020002}}
data["116_normal_1"] = { id = "116_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 116,  resoure_name = "0082_00_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.15,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {82000001}}
data["118_utl_1"] = { id = "118_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 118,  resoure_name = "0716_00_01",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.2,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {716000003}}
data["117_normal_1"] = { id = "117_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 117,  resoure_name = "0445_00_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.3,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {445000001}}
data["113_normal_1"] = { id = "113_normal_1",  logic_type = "immediate",  kind = "normal",  weight = 1,  heroId = 113,  resoure_name = "0006_02_00",  skill_name = "desc",  exchange_weather_id = 0,  skill_exchange_weather_time = 0,  animation_time = 1.15,  animation_name = "attack",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "move_to_target",  before_time = 0.0,  before_animation_name = "",  after_time = 0.0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {6020001}}
data["116_utl_1"] = { id = "116_utl_1",  logic_type = "immediate",  kind = "utl",  weight = 1,  heroId = 116,  resoure_name = "0082_00_00",  skill_name = "desc",  exchange_weather_id = 10,  skill_exchange_weather_time = 3.0,  animation_time = 1.6,  animation_name = "skill",  cd_time = 1.0,  select_target_obj_type = "enemy",  select_target_strategy_type = "base",  move_type = "stand_pos",  before_time = 0,  before_animation_name = "",  after_time = 0,  after_animation_name = "",  icon_name = "",  audio_name = "",  skill_effect_id = {82000002}}

return class_data
