-- this file is generated by program!
-- don't change it manaully.
-- source file: hero_type
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["feng"] = { id = "feng",  desc = "",  todo = ""}
data["huo"] = { id = "huo",  desc = "",  todo = ""}
data["gang"] = { id = "gang",  desc = "",  todo = ""}
data["shui"] = { id = "shui",  desc = "",  todo = ""}

return class_data
