-- this file is generated by program!
-- don't change it manaully.
-- source file: project_curve_type
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["line"] = { id = "line",  desc = "直线",  todo = ""}
data["curve"] = { id = "curve",  desc = "曲线",  todo = ""}

return class_data
