-- this file is generated by program!
-- don't change it manaully.
-- source file: scene_position
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end




function class_data.getDataByIndexOne(sence_res_id)

    if index_one_data == nil then
      class_data.initIndexOneData()
    end

    return index_one_data[sence_res_id]
end

function class_data.initIndexOneData()
    index_one_data = {}
    for k,v in pairs(data) do
        if index_one_data[v.sence_res_id] == nil then
          index_one_data[v.sence_res_id] = {}
        end

        index_one_data[v.sence_res_id][v.id] = v

    end
end
		
data[11] = { id = 11,  sence_res_id = "battle_scene_01",  scene_pos_id = 11,  pos_data = {-2,0,-3,0}}
data[12] = { id = 12,  sence_res_id = "battle_scene_01",  scene_pos_id = 12,  pos_data = {0,0,-2.5,0}}
data[13] = { id = 13,  sence_res_id = "battle_scene_01",  scene_pos_id = 13,  pos_data = {2,0,-3,0}}
data[14] = { id = 14,  sence_res_id = "battle_scene_01",  scene_pos_id = 14,  pos_data = {-2,0,-5.2,0}}
data[15] = { id = 15,  sence_res_id = "battle_scene_01",  scene_pos_id = 15,  pos_data = {0,0,-4.7,0}}
data[16] = { id = 16,  sence_res_id = "battle_scene_01",  scene_pos_id = 16,  pos_data = {2,0,-5.2,0}}
data[21] = { id = 21,  sence_res_id = "battle_scene_01",  scene_pos_id = 21,  pos_data = {2,0,3,-180}}
data[22] = { id = 22,  sence_res_id = "battle_scene_01",  scene_pos_id = 22,  pos_data = {0,0,2.5,-180}}
data[23] = { id = 23,  sence_res_id = "battle_scene_01",  scene_pos_id = 23,  pos_data = {-2,0,3,180}}
data[24] = { id = 24,  sence_res_id = "battle_scene_01",  scene_pos_id = 24,  pos_data = {2,0,5.2,-180}}
data[25] = { id = 25,  sence_res_id = "battle_scene_01",  scene_pos_id = 25,  pos_data = {0,0,4.7,-180}}
data[26] = { id = 26,  sence_res_id = "battle_scene_01",  scene_pos_id = 26,  pos_data = {-2,0,5.2,-180}}

return class_data
