-- this file is generated by program!
-- don't change it manaully.
-- source file: scene
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[1] = { sence_id = 1,  scene_type = "PVE",  sence_res_id = "battle_scene_01",  default_temperature = 50,  default_humidity = 50,  scene_attack_pos_id_s = {11,12,13,14,15,16},  scene_defence_pos_id_s = {21,22,23,24,25,26}}
data[2] = { sence_id = 2,  scene_type = "PVE",  sence_res_id = "battle_scene_01",  default_temperature = 50,  default_humidity = 50,  scene_attack_pos_id_s = {11,12,13,14,15,16},  scene_defence_pos_id_s = {21,22,23,24,25,26}}

return class_data
