-- this file is generated by program!
-- don't change it manaully.
-- source file: select_strategy_type
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["face_front_row"] = { id = "face_front_row",  desc = "前排",  todo = ""}
data["all"] = { id = "all",  desc = "所有人",  todo = ""}
data["min_hp"] = { id = "min_hp",  desc = "血量最少的人",  todo = ""}
data["face_back_row"] = { id = "face_back_row",  desc = "后排",  todo = ""}
data["face_col"] = { id = "face_col",  desc = "对位竖",  todo = ""}
data["random"] = { id = "random",  desc = "随机",  todo = ""}
data["base"] = { id = "base",  desc = "基本选人",  todo = ""}

return class_data
