-- this file is generated by program!
-- don't change it manaully.
-- source file: select_target_type
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["enemy"] = { id = "enemy",  desc = "敌人",  todo = ""}
data["all"] = { id = "all",  desc = "全部",  todo = ""}
data["friend_not_self"] = { id = "friend_not_self",  desc = "友方除自己",  todo = ""}
data["self"] = { id = "self",  desc = "自己",  todo = ""}
data["friend"] = { id = "friend",  desc = "友方",  todo = ""}

return class_data
