-- this file is generated by program!
-- don't change it manaully.
-- source file: skill_move_type
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data["move_to_target"] = { id = "move_to_target",  desc = "突击攻击",  todo = ""}
data["stand_pos"] = { id = "stand_pos",  desc = "原地攻击",  todo = ""}

return class_data
