-- this file is generated by program!
-- don't change it manaully.
-- source file: weather_exchange_particle
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[1] = { id = 1,  effect_id = 100,  enter_particle_show_time = 0.0,  enter_particle_args_name_s = {"max_particle"},  enter_particle_args_start_value_s = {0.0},  enter_particle_args_target_value_s = {50.0},  enter_particle_args_start_time_s = {0.0},  enter_particle_args_duration_s = {2.0},  leave_particle_args_name_s = {"max_particle"},  leave_particle_args_target_value_s = {2.0},  leave_particle_args_start_time_s = {0.0},  leave_particle_args_duration_s = {2.0},  leave_particle_unload_time = 5.0}
data[2] = { id = 2,  effect_id = 101,  enter_particle_show_time = 0.0,  enter_particle_args_name_s = {"max_particle"},  enter_particle_args_start_value_s = {0.0},  enter_particle_args_target_value_s = {50.0},  enter_particle_args_start_time_s = {0.0},  enter_particle_args_duration_s = {2.0},  leave_particle_args_name_s = {"max_particle"},  leave_particle_args_target_value_s = {2.0},  leave_particle_args_start_time_s = {0.0},  leave_particle_args_duration_s = {2.0},  leave_particle_unload_time = 5.0}
data[1001] = { id = 1001,  effect_id = 102,  enter_particle_show_time = 0.0,  enter_particle_args_name_s = {},  enter_particle_args_start_value_s = {},  enter_particle_args_target_value_s = {},  enter_particle_args_start_time_s = {},  enter_particle_args_duration_s = {},  leave_particle_args_name_s = {"start_color_a"},  leave_particle_args_target_value_s = {"0"},  leave_particle_args_start_time_s = {0.0},  leave_particle_args_duration_s = {1.0},  leave_particle_unload_time = 3.0}
data[801] = { id = 801,  effect_id = 103,  enter_particle_show_time = 0.0,  enter_particle_args_name_s = {},  enter_particle_args_start_value_s = {},  enter_particle_args_target_value_s = {},  enter_particle_args_start_time_s = {},  enter_particle_args_duration_s = {},  leave_particle_args_name_s = {"max_particle"},  leave_particle_args_target_value_s = {0.0},  leave_particle_args_start_time_s = {0.0},  leave_particle_args_duration_s = {2.0},  leave_particle_unload_time = 2.0}
data[201] = { id = 201,  effect_id = 101,  enter_particle_show_time = 0.0,  enter_particle_args_name_s = {},  enter_particle_args_start_value_s = {},  enter_particle_args_target_value_s = {},  enter_particle_args_start_time_s = {},  enter_particle_args_duration_s = {},  leave_particle_args_name_s = {"max_particle"},  leave_particle_args_target_value_s = {0.0},  leave_particle_args_start_time_s = {0.0},  leave_particle_args_duration_s = {2.0},  leave_particle_unload_time = 2.0}

return class_data
