-- this file is generated by program!
-- don't change it manaully.
-- source file: weather
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[1] = { weather_id = 1,  weather_type = "normal",  min_temperature = 0,  max_temperature = 30,  min_humidity = 0,  max_humidity = 30,  prefab_url = "ui/component/weather/Image_rain",  prefab_name = "Image_rain",  desc = "冰雹",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {},  weather_exchange_particle_id_s = {}}
data[2] = { weather_id = 2,  weather_type = "normal",  min_temperature = 31,  max_temperature = 70,  min_humidity = 0,  max_humidity = 30,  prefab_url = "ui/component/weather/Image_rain",  prefab_name = "Image_rain",  desc = "大晴天",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {201,202,203},  weather_exchange_particle_id_s = {201}}
data[3] = { weather_id = 3,  weather_type = "normal",  min_temperature = 71,  max_temperature = 100,  min_humidity = 0,  max_humidity = 30,  prefab_url = "ui/component/weather/Image_rain",  prefab_name = "Image_rain",  desc = "沙暴",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {},  weather_exchange_particle_id_s = {}}
data[4] = { weather_id = 4,  weather_type = "normal",  min_temperature = 0,  max_temperature = 30,  min_humidity = 31,  max_humidity = 70,  prefab_url = "ui/component/weather/Image_rain",  prefab_name = "Image_rain",  desc = "雾",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {101,102,103,104,105,106},  weather_exchange_particle_id_s = {}}
data[5] = { weather_id = 5,  weather_type = "normal",  min_temperature = 31,  max_temperature = 70,  min_humidity = 31,  max_humidity = 70,  prefab_url = "ui/component/weather/Image_rain",  prefab_name = "Image_rain",  desc = "晴天",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {501,502,503},  weather_exchange_particle_id_s = {}}
data[6] = { weather_id = 6,  weather_type = "normal",  min_temperature = 71,  max_temperature = 100,  min_humidity = 31,  max_humidity = 70,  prefab_url = "ui/component/weather/Image_sunny",  prefab_name = "     Image_sunny",  desc = "强日照",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {101,102,103,104,105,106},  weather_exchange_particle_id_s = {}}
data[7] = { weather_id = 7,  weather_type = "normal",  min_temperature = 0,  max_temperature = 30,  min_humidity = 71,  max_humidity = 100,  prefab_url = "ui/component/weather/Image_sunny",  prefab_name = "     Image_sunny",  desc = "下雪",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {},  weather_exchange_particle_id_s = {}}
data[8] = { weather_id = 8,  weather_type = "normal",  min_temperature = 31,  max_temperature = 70,  min_humidity = 71,  max_humidity = 100,  prefab_url = "ui/component/weather/Image_sunny",  prefab_name = "     Image_sunny",  desc = "下雨",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {801,802,803},  weather_exchange_particle_id_s = {801}}
data[9] = { weather_id = 9,  weather_type = "normal",  min_temperature = 71,  max_temperature = 100,  min_humidity = 71,  max_humidity = 100,  prefab_url = "ui/component/weather/Image_exposure",  prefab_name = "     Image_exposure",  desc = "乱流",  skill_effect_types = {"shui","huo"},  skill_effect_factors = {-0.2,0.2},  once_buff_id = {},  weather_echange_light_id = {},  weather_exchange_particle_id_s = {}}
data[10] = { weather_id = 10,  weather_type = "spetical",  min_temperature = 50,  max_temperature = 200,  min_humidity = 50,  max_humidity = 200,  prefab_url = "ui/component/weather/Image_exposure",  prefab_name = "     Image_exposure",  desc = "黑暗",  skill_effect_types = {"shui"},  skill_effect_factors = {0.2},  once_buff_id = {"buff_max_hp_sp1"},  weather_echange_light_id = {1001,1002,1003},  weather_exchange_particle_id_s = {1001}}

return class_data
