-- this file is generated by program!
-- don't change it manaully.
-- source file: weather_exchange_light
-- created at: 
-- copyright@zhouwei


local data = {}
local class_data = {}
local index_one_data = nil
class_data["data"] = data

function class_data.getDataByID(id)
    return data[id]
end



data[1] = { id = 1,  light_type = "player_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {3.0},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[2] = { id = 2,  light_type = "scene_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {7.0},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[3] = { id = 3,  light_type = "fog",  light_args_name_s = {"fog_color"},  light_args_target_value_s = {18,18,18},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[4] = { id = 4,  light_type = "fog",  light_args_name_s = {"fog_density"},  light_args_target_value_s = {1.0},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[503] = { id = 503,  light_type = "scene_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {1.8},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[801] = { id = 801,  light_type = "scene_light",  light_args_name_s = {"scene_light_color"},  light_args_target_value_s = {255,255,255},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[802] = { id = 802,  light_type = "fog",  light_args_name_s = {"fog_color"},  light_args_target_value_s = {72,182,150},  light_args_start_time_s = {2.0},  light_args_duration_s = {2.0}}
data[803] = { id = 803,  light_type = "scene_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {1.3},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[201] = { id = 201,  light_type = "scene_light",  light_args_name_s = {"scene_light_color"},  light_args_target_value_s = {255,255,255},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[202] = { id = 202,  light_type = "fog",  light_args_name_s = {"fog_color"},  light_args_target_value_s = {72,182,150},  light_args_start_time_s = {2.0},  light_args_duration_s = {2.0}}
data[203] = { id = 203,  light_type = "scene_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {2.3},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[101] = { id = 101,  light_type = "fog",  light_args_name_s = {"fog_color"},  light_args_target_value_s = {128,128,128},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[102] = { id = 102,  light_type = "fog",  light_args_name_s = {"fog_density"},  light_args_target_value_s = {0.01},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[103] = { id = 103,  light_type = "player_light",  light_args_name_s = {"player_light_color"},  light_args_target_value_s = {77,77,77},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[104] = { id = 104,  light_type = "scene_light",  light_args_name_s = {"scene_light_color"},  light_args_target_value_s = {255,255,255},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[1001] = { id = 1001,  light_type = "fog",  light_args_name_s = {"fog_color"},  light_args_target_value_s = {0,0,0},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[106] = { id = 106,  light_type = "scene_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {7.0},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[1003] = { id = 1003,  light_type = "scene_light",  light_args_name_s = {"scene_light_color"},  light_args_target_value_s = {0,0,0},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[501] = { id = 501,  light_type = "scene_light",  light_args_name_s = {"scene_light_color"},  light_args_target_value_s = {255,255,255},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}
data[502] = { id = 502,  light_type = "fog",  light_args_name_s = {"fog_color"},  light_args_target_value_s = {0,126,89},  light_args_start_time_s = {2.0},  light_args_duration_s = {2.0}}
data[105] = { id = 105,  light_type = "player_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {3.0},  light_args_start_time_s = {0.0},  light_args_duration_s = {3.0}}
data[1002] = { id = 1002,  light_type = "scene_light",  light_args_name_s = {"intensity"},  light_args_target_value_s = {0.29},  light_args_start_time_s = {0.0},  light_args_duration_s = {2.0}}

return class_data
