////this source code was auto-generated by tolua#, do not modify it
//using System;
//using LuaInterface;
//
//public class DynamicLoadASyncerWrap
//{
//	public static void Register(LuaState L)
//	{
//		L.BeginClass(typeof(DynamicLoadASyncer), typeof(System.Object));
//		L.RegFunction("StartLoadAsync", StartLoadAsync);
//		L.RegFunction("CancelLoading", CancelLoading);
//		L.RegFunction("New", _CreateDynamicLoadASyncer);
//		L.RegFunction("__tostring", ToLua.op_ToString);
//		L.RegVar("path", get_path, set_path);
//		L.RegVar("userData", get_userData, set_userData);
//		L.RegVar("loadDone", get_loadDone, set_loadDone);
//		L.RegVar("manager", get_manager, set_manager);
//		L.EndClass();
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int _CreateDynamicLoadASyncer(IntPtr L)
//	{
//		try
//		{
//			int count = LuaDLL.lua_gettop(L);
//
//			if (count == 0)
//			{
//				DynamicLoadASyncer obj = new DynamicLoadASyncer();
//				ToLua.PushObject(L, obj);
//				return 1;
//			}
//			else
//			{
//				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DynamicLoadASyncer.New");
//			}
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int StartLoadAsync(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)ToLua.CheckObject(L, 1, typeof(DynamicLoadASyncer));
//			obj.StartLoadAsync();
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int CancelLoading(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)ToLua.CheckObject(L, 1, typeof(DynamicLoadASyncer));
//			obj.CancelLoading();
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int get_path(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			string ret = obj.path;
//			LuaDLL.lua_pushstring(L, ret);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index path on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int get_userData(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			object ret = obj.userData;
//			ToLua.Push(L, ret);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index userData on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int get_loadDone(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			DynamicLoadASyncManager.LoadASyncDone ret = obj.loadDone;
//			ToLua.Push(L, ret);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index loadDone on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int get_manager(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			DynamicLoadASyncManager ret = obj.manager;
//			ToLua.Push(L, ret);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index manager on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int set_path(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			string arg0 = ToLua.CheckString(L, 2);
//			obj.path = arg0;
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index path on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int set_userData(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			object arg0 = ToLua.ToVarObject(L, 2);
//			obj.userData = arg0;
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index userData on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int set_loadDone(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			DynamicLoadASyncManager.LoadASyncDone arg0 = null;
//			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);
//
//			if (funcType2 != LuaTypes.LUA_TFUNCTION)
//			{
//				 arg0 = (DynamicLoadASyncManager.LoadASyncDone)ToLua.CheckObject(L, 2, typeof(DynamicLoadASyncManager.LoadASyncDone));
//			}
//			else
//			{
//				LuaFunction func = ToLua.ToLuaFunction(L, 2);
//				arg0 = DelegateFactory.CreateDelegate(typeof(DynamicLoadASyncManager.LoadASyncDone), func) as DynamicLoadASyncManager.LoadASyncDone;
//			}
//
//			obj.loadDone = arg0;
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index loadDone on a nil value" : e.Message);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int set_manager(IntPtr L)
//	{
//		object o = null;
//
//		try
//		{
//			o = ToLua.ToObject(L, 1);
//			DynamicLoadASyncer obj = (DynamicLoadASyncer)o;
//			DynamicLoadASyncManager arg0 = (DynamicLoadASyncManager)ToLua.CheckUnityObject(L, 2, typeof(DynamicLoadASyncManager));
//			obj.manager = arg0;
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index manager on a nil value" : e.Message);
//		}
//	}
//}
//
