////this source code was auto-generated by tolua#, do not modify it
//using System;
//using LuaInterface;
//
//public class DynamicLoadASyncManagerWrap
//{
//	public static void Register(LuaState L)
//	{
//		L.BeginClass(typeof(DynamicLoadASyncManager), typeof(UnityEngine.MonoBehaviour));
//		L.RegFunction("LoadASync", LoadASync);
//		L.RegFunction("DeleteASyncer", DeleteASyncer);
//		L.RegFunction("OnLoadASyncerReturn", OnLoadASyncerReturn);
//		L.RegFunction("__eq", op_Equality);
//		L.RegFunction("__tostring", ToLua.op_ToString);
//		L.RegVar("Instance", get_Instance, null);
//		L.RegFunction("LoadASyncDone", DynamicLoadASyncManager_LoadASyncDone);
//		L.EndClass();
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int LoadASync(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 4);
//			DynamicLoadASyncManager obj = (DynamicLoadASyncManager)ToLua.CheckObject(L, 1, typeof(DynamicLoadASyncManager));
//			string arg0 = ToLua.CheckString(L, 2);
//			DynamicLoadASyncManager.LoadASyncDone arg1 = null;
//			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);
//
//			if (funcType3 != LuaTypes.LUA_TFUNCTION)
//			{
//				 arg1 = (DynamicLoadASyncManager.LoadASyncDone)ToLua.CheckObject(L, 3, typeof(DynamicLoadASyncManager.LoadASyncDone));
//			}
//			else
//			{
//				LuaFunction func = ToLua.ToLuaFunction(L, 3);
//				arg1 = DelegateFactory.CreateDelegate(typeof(DynamicLoadASyncManager.LoadASyncDone), func) as DynamicLoadASyncManager.LoadASyncDone;
//			}
//
//			object arg2 = ToLua.ToVarObject(L, 4);
//			DynamicLoadASyncer o = obj.LoadASync(arg0, arg1, arg2);
//			ToLua.PushObject(L, o);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int DeleteASyncer(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 2);
//			DynamicLoadASyncManager obj = (DynamicLoadASyncManager)ToLua.CheckObject(L, 1, typeof(DynamicLoadASyncManager));
//			DynamicLoadASyncer arg0 = (DynamicLoadASyncer)ToLua.CheckObject(L, 2, typeof(DynamicLoadASyncer));
//			obj.DeleteASyncer(arg0);
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int OnLoadASyncerReturn(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 2);
//			DynamicLoadASyncManager obj = (DynamicLoadASyncManager)ToLua.CheckObject(L, 1, typeof(DynamicLoadASyncManager));
//			DynamicLoadASyncer arg0 = (DynamicLoadASyncer)ToLua.CheckObject(L, 2, typeof(DynamicLoadASyncer));
//			obj.OnLoadASyncerReturn(arg0);
//			return 0;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int op_Equality(IntPtr L)
//	{
//		try
//		{
//			ToLua.CheckArgsCount(L, 2);
//			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
//			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
//			bool o = arg0 == arg1;
//			LuaDLL.lua_pushboolean(L, o);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int get_Instance(IntPtr L)
//	{
//		try
//		{
//			ToLua.Push(L, DynamicLoadASyncManager.Instance);
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//
//	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
//	static int DynamicLoadASyncManager_LoadASyncDone(IntPtr L)
//	{
//		try
//		{
//			int count = LuaDLL.lua_gettop(L);
//			LuaFunction func = ToLua.CheckLuaFunction(L, 1);
//
//			if (count == 1)
//			{
//				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(DynamicLoadASyncManager.LoadASyncDone), func);
//				ToLua.Push(L, arg1);
//			}
//			else
//			{
//				LuaTable self = ToLua.CheckLuaTable(L, 2);
//				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(DynamicLoadASyncManager.LoadASyncDone), func, self);
//				ToLua.Push(L, arg1);
//			}
//			return 1;
//		}
//		catch(Exception e)
//		{
//			return LuaDLL.toluaL_exception(L, e);
//		}
//	}
//}
//
