//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class StringUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("StringUtil");
		L.RegFunction("GetSplitString", GetSplitString);
		L.RegFunction("GetDynamicParams", GetDynamicParams);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSplitString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string[] o = StringUtil.GetSplitString(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDynamicParams(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.List<string> arg0 = (System.Collections.Generic.List<string>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<string>));
			System.Collections.Generic.Dictionary<string,string> o = StringUtil.GetDynamicParams(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

