//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Texture2DManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Texture2DManager), typeof(System.Object));
		L.RegFunction("Release", Release);
		L.RegFunction("CreateTextureAuto", CreateTextureAuto);
		L.RegFunction("CreateTextureByImage", CreateTextureByImage);
		L.RegFunction("CleanAllCache", CleanAllCache);
		L.RegFunction("ClearUnusedAllCache", ClearUnusedAllCache);
		L.RegFunction("New", _CreateTexture2DManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("TEXTURE_SIZE", 128);
		L.RegConstant("CACHE_MAX_SIZE", 64);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTexture2DManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Texture2DManager obj = new Texture2DManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Texture2DManager.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Release(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Texture2DManager.Release();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateTextureAuto(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			Texture2DManager obj = (Texture2DManager)ToLua.CheckObject(L, 1, typeof(Texture2DManager));
			UnityEngine.UI.RawImage arg0 = (UnityEngine.UI.RawImage)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.UI.RawImage));
			string arg1 = ToLua.CheckString(L, 3);
			bool arg2;
			bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
			int arg4 = (int)LuaDLL.luaL_checknumber(L, 6);
			UnityEngine.Texture2D o = obj.CreateTextureAuto(arg0, arg1, out arg2, arg3, arg4);
			ToLua.Push(L, o);
			LuaDLL.lua_pushboolean(L, arg2);
			return 2;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateTextureByImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Texture2DManager obj = (Texture2DManager)ToLua.CheckObject(L, 1, typeof(Texture2DManager));
			UnityEngine.UI.RawImage arg0 = (UnityEngine.UI.RawImage)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.UI.RawImage));
			string arg1 = ToLua.CheckString(L, 3);
			bool arg2;
			UnityEngine.Texture2D o = obj.CreateTextureByImage(arg0, arg1, out arg2);
			ToLua.Push(L, o);
			LuaDLL.lua_pushboolean(L, arg2);
			return 2;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CleanAllCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Texture2DManager obj = (Texture2DManager)ToLua.CheckObject(L, 1, typeof(Texture2DManager));
			obj.CleanAllCache();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearUnusedAllCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Texture2DManager obj = (Texture2DManager)ToLua.CheckObject(L, 1, typeof(Texture2DManager));
			obj.ClearUnusedAllCache();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Texture2DManager.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

