-- This file is generated by program!
-- Don't change it manaully.
-- Created at: Mon Mar 28 06:16:09 2016


local string_table =
{	["helloTxt"] = "你好",
	["noTxt"] = "取消",
	["okTxt"] = "确定",
  ["round_desc"] = "回合",
  ["order_desc"] = "场战斗",
  ["battle_win"] = "战斗胜利",
  ["battle_lose"] = "战斗失败",
}

function string_table.get_text(key, ...)
	return string.format(string_table[key], ...);
end

function string_table.get_temp_text(key, ...)
	return string.format(key, ...);
end

return string_table